default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: achieve_development
test:
  <<: *default
  database: achieve_test

production:
  <<: *default
  database: achieve_production
  username: achieve
  password: <%= ENV['SAMPLE_DATABASE_PASSWORD'] %>